services:
  fast_inspection_inspection_controller_ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3003}
      HOST: ${HOST:-fast_inspection_inspection_controller_ms}
      DB_NAME: ${DB_NAME:-building_controller_db}
      DB_HOST: ${DB_HOST:-fast_inspection_mongo_db_server}
      DB_PORT: ${DB_PORT:-27018}
      DB_USERNAME: ${DB_USERNAME:-adrian}
      DB_PASSWORD: ${DB_PASSWORD:-12345678}
      CONFIGS_SERVICE_HOST: ${CONFIGS_SERVICE_HOST:-fast_inspection_config_ms}
      CONFIGS_SERVICE_PORT: ${CONFIGS_SERVICE_PORT:-3001}
    ports:
      - "${PORT:-3003}:${PORT:-3003}"
    networks:
      - fast_inspection_network

  
networks:
  fast_inspection_network:
    name: fast_inspection_network

